apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: speech-to-nlu
  name: speech-to-nlu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: speech-to-nlu
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: speech-to-nlu
    spec:
      containers:
      - args:
        - npm
        - start
        image: speech-to-nlu
        imagePullPolicy: ""
        name: speech-to-nlu
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app
          name: speech-to-nlu-claim0
        - mountPath: /usr/src/app/node_modules
          name: speech-to-nlu-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: speech-to-nlu-claim0
        persistentVolumeClaim:
          claimName: speech-to-nlu-claim0
      - name: speech-to-nlu-claim1
        persistentVolumeClaim:
          claimName: speech-to-nlu-claim1
status: {}
